- hosts: "postfix"
  become: yes
  tasks:

    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest

    - name: apt upgrade - dist upgrade
      apt:
        upgrade: 'yes'

    - name: Remove useless packages from the cache
      ansible.builtin.apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes    


    ---
    - name: Install Postfix
      hosts: postfix
      become: yes

      tasks:
        - name: Update package cache
        apt:
          update_cache: yes

        - name: Install Postfix
          apt:
            name: postfix
            state: present

        - name: Configure Postfix
          debconf:
          name: postfix
          question: "postfix/main_mailer_type"
          value: "Internet Site"
          vtype: "string"
          state: "present"
        with_items:
          - example.com
        notify: Restart Postfix

      handlers:
        - name: Restart Postfix
          service:
            name: postfix
            state: restarted




#    - name: pihole -up Execute the command in remote shell; stdout goes to the specified file on the remote
#      ansible.builtin.shell: piholeup.sh >> ./lastpiholeupdate.txt    
#      args:
#        executable: /bin/bash
 