- hosts: "pihole"
  become: yes
  tasks:

    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest

    - name: apt upgrade - dist upgrade
      apt:
        upgrade: 'yes'

    - name: Remove useless packages from the cache
      ansible.builtin.apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes    

    - name: pihole -up Execute the command in remote shell; stdout goes to the specified file on the remote
      ansible.builtin.shell: ./piholeup.sh >> ./lastpiholeupdate.txt    
 