- hosts: "pihole"
  become: yes
  tasks:

    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest

    - name: apt upgrade - dist upgrade
      apt:
        upgrade: 'yes'

    - name: Remove useless packages from the cache
      ansible.builtin.apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes    

  #  - name: Add an Apt signing key, uses whichever key is at the URL
  #    ansible.builtin.apt_key:
  #      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
  #      state: present  
  #  - name: apt
  #    apt:
#        update_cache: yes       failing with error
  #      upgrade: 'yes'  
  